"""junction table ingredients_list renamed to RecipeIngredients

Revision ID: 579141f01d7c
Revises: 2961d93175ba
Create Date: 2019-06-19 13:53:06.417413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579141f01d7c'
down_revision = '2961d93175ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('ingredients_list', 'RecipeIngredients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('RecipeIngredients', 'ingredients_list')
    # ### end Alembic commands ###
