"""junction table ingredients_list renamed to RecipeIngredients

Revision ID: 579141f01d7c
Revises: 2961d93175ba
Create Date: 2019-06-19 13:53:06.417413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579141f01d7c'
down_revision = '2961d93175ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RecipeIngredients',
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], )
    )
    op.drop_table('ingredients_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients_list',
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.Column('ingredient_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], )
    )
    op.drop_table('RecipeIngredients')
    # ### end Alembic commands ###
